use_frameworks!

platform :ios, '9.0'

target 'AMKLaunchTimeProfiler_Example' do
  pod 'AMKLaunchTimeProfiler', :path => '../'

  target 'AMKLaunchTimeProfiler_Tests' do
    inherit! :search_paths

    
  end
end
